
[functions.create_staff_user]
enabled = true
verify_jwt = false
import_map = "./functions/create_staff_user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create_staff_user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create_staff_user/*.html" ]

[functions.upload_product_image]
enabled = true
verify_jwt = true
import_map = "./functions/upload_product_image/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upload_product_image/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upload_product_image/*.html" ]

[functions.delete_staff_user]
enabled = true
verify_jwt = false
entrypoint = "./functions/delete_staff_user/index.ts"

[functions.set_staff_password]
enabled = true
verify_jwt = false
import_map = "./functions/set_staff_password/deno.json"
entrypoint = "./functions/set_staff_password/index.ts"

[functions.verify_password]
enabled = true
verify_jwt = false
import_map = "./functions/verify_password/deno.json"
entrypoint = "./functions/verify_password/index.ts"

[functions.server_time]
enabled = true
verify_jwt = false
import_map = "./functions/server_time/deno.json"
entrypoint = "./functions/server_time/index.ts"

[functions.impersonate_business]
enabled = true
verify_jwt = false
import_map = "./functions/impersonate_business/deno.json"
entrypoint = "./functions/impersonate_business/index.ts"

[functions.fiscal_profile]
enabled = true
verify_jwt = true
import_map = "./functions/fiscal_profile/deno.json"
entrypoint = "./functions/fiscal_profile/index.ts"

[functions.fdms_health]
enabled = true
verify_jwt = true
import_map = "./functions/fdms_health/deno.json"
entrypoint = "./functions/fdms_health/index.ts"

[functions.fiscal_credentials]
enabled = true
verify_jwt = true
import_map = "./functions/fiscal_credentials/deno.json"
entrypoint = "./functions/fiscal_credentials/index.ts"

[functions.fiscal_devices]
enabled = true
verify_jwt = true
import_map = "./functions/fiscal_devices/deno.json"
entrypoint = "./functions/fiscal_devices/index.ts"

[functions.fiscal_submissions]
enabled = true
verify_jwt = true
import_map = "./functions/fiscal_submissions/deno.json"
entrypoint = "./functions/fiscal_submissions/index.ts"

[functions.fdms_worker]
enabled = true
verify_jwt = false
import_map = "./functions/fdms_worker/deno.json"
entrypoint = "./functions/fdms_worker/index.ts"
